# Generated by Django 3.1.2 on 2020-11-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('usado', models.BooleanField()),
            ],
        ),
    ]
